env:
  global:
    - NODE_ENV=test
language: node_js
node_js:
  - 'stable'
<<<<<<< HEAD
=======
install:
  - npm install
>>>>>>> 76af3817a1f520aea42f993fea557dad094091c6
services:
  - postgresql
before_script:
  - psql -c 'create database test_db;' -U postgres
script: 
<<<<<<< HEAD
  - npm install
  - npm test
after_success: 
  - npm run coverage
=======
  - npm test
>>>>>>> 76af3817a1f520aea42f993fea557dad094091c6
