version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  run_tests:
    docker:
      - image:  circleci/node:10
      - image: circleci/postgres:10
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: circleci
          POSTGRES_PASSWORD:  okayfine

    environment:
      NODE_ENV: test
      POSTGRES_USER: circleci
      POSTGRES_DB: circleci
      JWT_SECRET: secret
    steps:

      - run:
          name: Install ltree extension for Postgres
          command: |
            sudo apt-get update
            sudo apt-get install postgresql-client
            dockerize -wait tcp://localhost:5432 -timeout 1m
            psql -U circleci -h localhost -p 5432 -c 'create extension ltree'
      - checkout
      - run:
          name: Install npm dependencies
          command: npm install --save
      - run:
          name: run tests
          command: 
            npm run test
workflows:
  builds:
    jobs: 
      - run_tests